name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Extract version from tag name
      uses: olegtarasov/get-tag@v2.1
      id: tagName
              
    - name: Publish BuildNotificiations
      run: dotnet publish BuildNotifications\BuildNotifications.csproj -c Release -r win-x64 /p:Version=${{ steps.tagName.outputs.tag }} /p:FileVersion=${{ steps.tagName.outputs.tag }} /p:AssemblyVersion=${{ steps.tagName.outputs.tag }}
    
    - name: Publish BuildNotificiations.Core
      run: dotnet publish BuildNotifications.Core\BuildNotifications.Core.csproj -c Release -r win-x64 /p:Version=${{ steps.tagName.outputs.tag }} /p:FileVersion=${{ steps.tagName.outputs.tag }} /p:AssemblyVersion=${{ steps.tagName.outputs.tag }}
      
    - name: Publish TFS Plugin
      run: dotnet publish Plugins\BuildNotifications.Plugin.Tfs\BuildNotifications.Plugin.Tfs.csproj -c Release -r win-x64 /p:Version=${{ steps.tagName.outputs.tag }} /p:FileVersion=${{ steps.tagName.outputs.tag }} /p:AssemblyVersion=${{ steps.tagName.outputs.tag }}
      
    - name: Publish ToastNotificationsPlugin
      run: dotnet publish Plugins\ToastNotificationsPlugin\ToastNotificationsPlugin.csproj -c Release -r win-x64 /p:Version=${{ steps.tagName.outputs.tag }} /p:FileVersion=${{ steps.tagName.outputs.tag }} /p:AssemblyVersion=${{ steps.tagName.outputs.tag }}

    - name: Create package
      run: Scripts/create-release-package.ps1 -versionToBuild ${{ steps.tagName.outputs.tag }} -workingDirectory ${{ github.workspace }}
      
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "Releases/RELEASES,Releases/Setup.exe,Releases/*-full.nupkg,Releases/*-delta.nupkg"
        draft: true
